### ISSUE TITLE
Using a relative directory for specifying feature-files yields an exception

### ISSUE THREAD

**Issue by EdwinVW** [Augurk/Augurk.CommandLine#6]
When using a relative path to a directory containing multiple feature-files yields a _DirectoryNotFoundException_. The first file will be processed successfully, but for all the other files the exception occurs.

**Repo steps:**
0. Make sure you have an Augurk web-app up and running (in my case on _http://localhost:5555/Augurk_).
1. Create folder and copy the Augurk command-line tool there.
2. Create folder inside this folder named _FeatureFiles_ and copy multiple feature-files into it.
3. Execute the following command-line: `augurk.exe publish --groupName "GroupName" --url "http://localhost:5555/Augurk" --featureFiles "FeatureFiles"`

**Result:**
```
Starting publishing of feature files...
Succesfully published feature 'Calculator' to group 'GroupName' for branch .
An exception occured while uploading feature file 'FeatureFiles\Feature2.feature
System.IO.DirectoryNotFoundException: Could not find a part of the path 'd:\dev\git\Augurk.CommandLine\src\Augurk.CommandLine\bin\Debug\FeatureFiles\FeatureFiles\Feature2.feature'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Augurk.CommandLine.Commands.PublishCommand.ParseFeatureFile(String featureFile) in d:\dev\git\Augurk.CommandLine\src\Augurk.CommandLine\Commands\PublishCommand.cs:line 253
   at Augurk.CommandLine.Commands.PublishCommand.PublishFeatureFiles() in d:\dev\git\Augurk.CommandLine\src\Augurk.CommandLine\Commands\PublishCommand.cs:line 89
Done publishing feature files.
```
**Issue:**
The issue is caused by a bug in the _ParseFeatureFile_ method of the _PublishCommand_. In this method, the current directory is changed, but not reset to the previous directory afterwards. This causes all successive calls to fail because the specified feature-file (including directory information) cannot be found.

**Comment by EdwinVW** [comment]
PR with fix was merged.
